on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  main:
    name: Update App Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Homey App â€” Publish
        uses: athombv/github-action-homey-app-publish@v1
        id: publish
        with:
          personal_access_token: ${{ secrets.HOMEY_PAT }}

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
